### ISSUE TITLE
Logger initialization failure on Chapter 07 - grocery_store.py

### ISSUE THREAD

**Issue by ds1dbx** [PacktPublishing/Cloud-Native-Observability#25]
As OTLPHandler was already changed to LogginHandler, I'm trying to update grocery_store.py code on Chapter 07 to working with new handler.
I'm using `opentelemetry-sdk` and `opentelemetry-api` version `1.18.0`, which looks stable version at the moment.
I've updated code like as below, but resulted in logger provider initializing error.

*Code changed (import statement and dictConfig object statement)*
```from logging.config import dictConfig
import requests
from flask import Flask
from opentelemetry.instrumentation.wsgi import OpenTelemetryMiddleware

dictConfig(
    {
        "version": 1,
        "handlers": {
            "otlp": {
                "class": "opentelemetry.sdk._logs.LoggingHandler"
            }
        },
        "root": {"level": "DEBUG", "handlers": ["otlp"]}
    }
)

app = Flask(__name__)
app.wsgi_app = OpenTelemetryMiddleware(app.wsgi_app)

@app.route("/")
def welcome():
    return "Welcome to the grocery store!"

@app.route("/products")
def products():
    url = "http://localhost:5001/inventory"
    resp = requests.get(url)
    return resp.text

if __name__ == "__main__":
    app.run(port=5000)
```

What I tried env variables are as below

```
OTEL_RESOURCE_ATTRIBUTES="service.name=grocery-store,
                       service.version=0.1.2,
                       net.host.name='hostname',
                       net.host.ip='ipconfig getifaddr en0'" \
  OTEL_TRACES_EXPORTER=console \
  OTEL_PYTHON_TRACER_PROVIDER=sdk \
  OTEL_METRICS_EXPORTER=console \
  OTEL_PYTHON_METER_PROVIDER=sdk \
  OTEL_LOGS_EXPORTER=console \
  OTEL_PYTHON_LOGGER_PROVIDER=sdk \
  OTEL_PROPAGATORS=b3,tracecontext \
  opentelemetry-instrument python grocery_store.py
```

And main part of runtime error shows `Failed to load configured provider logger_provider` and here's full error messages.

```
Failed to load configured provider logger_provider
Traceback (most recent call last):
  File "/Users/nopd/dev/opentelemetry_book/Cloud-Native-Observability/cloud_native_observability/lib/python3.9/site-packages/opentelemetry/util/_providers.py", line 43, in _load_provider
    next(  # type: ignore
StopIteration
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/logging/config.py", line 564, in configure
    handler = self.configure_handler(handlers[name])
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/logging/config.py", line 745, in configure_handler
    result = factory(**kwargs)
  File "/Users/nopd/dev/opentelemetry_book/Cloud-Native-Observability/cloud_native_observability/lib/python3.9/site-packages/opentelemetry/sdk/_logs/_internal/__init__.py", line 330, in __init__
    self._logger_provider = logger_provider or get_logger_provider()
  File "/Users/nopd/dev/opentelemetry_book/Cloud-Native-Observability/cloud_native_observability/lib/python3.9/site-packages/opentelemetry/_logs/_internal/__init__.py", line 182, in get_logger_provider
    logger_provider: LoggerProvider = _load_provider(  # type: ignore
  File "/Users/nopd/dev/opentelemetry_book/Cloud-Native-Observability/cloud_native_observability/lib/python3.9/site-packages/opentelemetry/util/_providers.py", line 43, in _load_provider
    next(  # type: ignore
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/nopd/dev/opentelemetry_book/Cloud-Native-Observability/ch04/grocery_store.py", line 7, in <module>
    dictConfig(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/logging/config.py", line 809, in dictConfig
    dictConfigClass(config).configure()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/logging/config.py", line 571, in configure
    raise ValueError('Unable to configure handler '
ValueError: Unable to configure handler 'otlp'
{
    "resource_metrics": [
        {
            "resource": {
                "attributes": {
                    "telemetry.sdk.language": "python",
                    "telemetry.sdk.name": "opentelemetry",
                    "telemetry.sdk.version": "1.18.0",
                    "service.name": "grocery-store",
                    "service.version": "0.1.2",
                    "net.host.name": "'hostname'",
                    "net.host.ip": "'ipconfig getifaddr en0'",
                    "telemetry.auto.version": "0.39b0"
                },
                "schema_url": ""
            },
            "scope_metrics": [],
            "schema_url": ""
        }
    ]
}
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 2141, in shutdown
    h.flush()
  File "/Users/nopd/dev/opentelemetry_book/Cloud-Native-Observability/cloud_native_observability/lib/python3.9/site-packages/opentelemetry/sdk/_logs/_internal/__init__.py", line 388, in flush
    self._logger_provider.force_flush()
AttributeError: 'LoggingHandler' object has no attribute '_logger_provider'
```

I'm not quiet sure why initialization is failing.

**Comment by ds1dbx** [comment]
Same initializing error occurred for `shopper.py` also. It looks assigning `LoggingHandler` to python logging hander causing the issue. Not quiet sure `LoggingHandler()` is why not acceptable as a logging handler.
